frida/frida-python

- src/frida/tracer.py
> Prevent detecting void as an argument in manpages

- src/frida/__init__.py
- src/frida/application.py
- src/frida/repl.py
Using autoreset=True in colorama's init function, causes it to wrap
stdin.
This is problematic because readline also messes with stdin, and
causes readline to stop working.
The solution is to simply not use autoreset=True, and then (at least
on non-windows platforms) stdin will not be wrapped
To see the issue - run frida-repl with and without the patch. Without
the patch the arrow keys won't work and will spit control codes, with
the patch everything will work as expected
> Fix colorama/readline collision

- src/frida/tracer.py
_create_stub_handler() of tracer.py failed with unicode error when handling manual pages containing unicode characters (tested with openat on Ubuntu 12.04). This commit makes the function handle unicode errors gracefully by replacing problematic characters.
> Gracefully handling unicode errors

- src/frida/repl.py
For instance `NULL.<TAB>` would do nothing before, but it will now show `isNull`, `add`, `sub`, etc.
> Add prototype names to repl autocomplete

- src/frida/__init__.py
- src/frida/application.py
- src/frida/core.py
- src/frida/discoverer.py
- src/frida/ps.py
- src/frida/repl.py
- src/frida/tracer.py
I also got rid of the executable bits on `application.py`.
> Improve compatibility between Python 2 and 3

- src/frida/tracer.py
Modify the manpage parser regexp to select only the first occurrence of the "TYPE FUNCTION(TYPE ARG, ...)", including multiline function prototypes.
https://github.com/frida/frida-python/issues/62
The proposed pull request should take the first match on a function prototype:
* if defined on one line, like `int open(const char *pathname, int flags);`
* if defined with varargs, like `int ioctl(int d, unsigned long request, ...);`
* if defined on multiple lines, like
```
void *mmap(void *addr, size_t length, int prot, int flags,
int fd, off_t offset);
```
* and also when the return type is a pointer of arbitrary depth, like `*mmap`
> Fix the manpage parser regexp

- src/frida/application.py
Tested on Windows against Python 2.7.8 and 3.5.1 with cmd (cp-437).
Was previously printing out:
```
b"    _____\n   (_____)\n    |   |    Frida 6.0.4 - A world-class dynamic instrumentation framework\n    |   |
\n    |`-'|    Commands:\n    |   |        help      -> Displays the help system\n    |   |        object?   -
> Display information about 'object'\n    |   |        exit/quit -> Exit\n    |   |\n    |   |    More info at
http://www.frida.re/docs/home/\n    `._.'\n"
```
> Fix Python 3 line endings/encoding regression

- frida-python27.vcxproj
- frida-python35.vcxproj
Python for Windows cannot be installed in a way that will satisfy the current build configuration. This is a small step in the right direction.
> Add solution-local python references for future Windows build enhancements

- src/_frida.c
pyconfig.h authors believe it is helpful to pepper their header with pragma lib directives hinging on the generic _DEBUG identifier, forcing the linker to attempt linkage with libs that don't ship with Python 2.x. This change eliminates the need to build Python from scratch or edit the Python include.
This change can be overridden at compile time via _FRIDA_ENABLE_PYDEBUG.
> Resolve pyconfig pain point in Windows build scenario

- src/frida/repl.py
I've modified `FridaCompleter` to use `re.search` such that auto-completions will be case-insensitive as well as position-insensitive (as opposed to `startswith`).
User input is escaped with `re.escape`.
> Improve REPL autocompletion

- src/frida/application.py
- src/frida/repl.py
Currently, the application waits for the user to start the application using %resume. This patch adds a --nopause argument that automatically calls %resume so that no further user interaction is required.
> Added ability to not-pause at startup

- src/_frida.c
This fixes a bug that ValueError is raised when off() called on an
instance method and not a simple python function.
> Compare signal callbacks as PyObjects and not as pointers

- src/frida/application.py
I find it useful to record the Frida output to a logfile, especially for long runs. The repl _resists_ regular means such as tee and redirection, so I added this option.
> added option to write all repl prints to a logfile

- src/frida/repl.py
Fixes #118.
This was a small bug where the prompt string wasn't being passed to the `input_impl` method, so it never displayed the yes/no prompt.
> Fix small bug in prompting for codeshare

- src/frida/application.py
This error occurs when pressing a key in the console window of a frida-trace session on Windows (Python 3.6)
```
gTraceback (most recent call last):
File "C:\Program Files (x86)\Python36-32\Scripts\frida-trace-script.py", line 11, in <module>
load_entry_point('frida==10.3.8', 'console_scripts', 'frida-trace')()
File "c:\program files (x86)\python36-32\lib\site-packages\frida\tracer.py", line 866, in main
app.run()
File "c:\program files (x86)\python36-32\lib\site-packages\frida\application.py", line 163, in run
self._reactor.run()
File "c:\program files (x86)\python36-32\lib\site-packages\frida\application.py", line 388, in run
self._run_until_return(self)
File "c:\program files (x86)\python36-32\lib\site-packages\frida\tracer.py", line 818, in _await_ctrl_c
input_with_timeout(0.5)
File …
```
> fix TypeError when reading console input on windows

- src/frida/application.py
This fixes the following error:
```
Traceback (most recent call last):
File "frida/core.py", line 394, in _on_message
self._log_handler(level, text)
File "frida/repl.py", line 74, in _log
ConsoleApplication._log(self, level, text)
File "frida/application.py", line 334, in _log
self._print(text)
File "frida/application.py", line 326, in _print
encoded_args.append(arg.encode(encoding, errors='replace').decode(decoder)) # , errors='replace'
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 1249-1254: truncated \UXXXXXXXX escape
```
> Bug fix: Handle unicode decoding errors with replacing

- src/frida/repl.py
1. Make frida request input using raw_input when running in emacs shell.
2. The get_input requests one parameter, so give it to satisfy an angry python exception.
3. Im not sure if the "have_terminal" should be true only when the stdin is a file. If so, the os.environ.get("TERM", '') == "dumb" should be inside the "if have_terminal" if, with get_input instead using CommandLineInteface.
> [Frida-Python][Terminal] Call raw_input from emacs shell

- src/setup.py
https://pypi.org/project/frida/ doesn't render README.md as Markdown:
---
---
But the good news is now that the new PyPI (aka Warehouse) has been released, Markdown is supported.
More info and examples:
* https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
* https://github.com/di/markdown-description-example
* https://pypi.org/project/markdown-description-example/
> Show long description with Markdown on PyPI

- src/setup.py
Python 2.6 and 3.0-3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team.
They're also little used.
Here's the pip installs for Frida from PyPI for May 2018:
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  72.70% |          2,402 |
| 3.6            |  21.43% |            708 |
| 3.5            |   4.60% |            152 |
| 3.4            |   0.88% |             29 |
| 3.7            |   0.27% |              9 |
| 2.6            |   0.06% |              2 |
| 3.8            |   0.03% |              1 |
| None           |   0.03% |              1 |
| Total          |         |          3,304 |
Source:
`pypinfo --start-date 2018-05-01 --end-date 2018-05-31 --percent --markdown frida …
> Declare explicit support for maintained Python versions

- frida/core.py
- expose the default log handler
- remove the ability to reset the log handler by setting it to `None`
- add `get_log_handler()`
> Refactor log handler access logic

- setup.py
- tests/test_pep503_page_parser.py
Fix #141 
I couldn't test it on my environment, because I don't know what `FRIDA_EXTENSION` is. So I wrote a unittest for `PEP503PageParser`.
It is not easy to write a HTML parser, but I'm not sure if is it good to add a new third-party dependency to `pyproject.toml`.
(BTW, python2 is horrible for me. 😂)
(English is not my first language, please forgive my poor English.)
> Use PEP 503 instead of pypi xmlrpc to support mirrors (Fix #141)

- setup.py
`get_index_url_from_pip` returns bytes but `normalize_url` needs str
> setup: Fix "TypeError: endswith first arg must be bytes or a tuple of bytes, not str"

- frida/core.py
- pyproject.toml
- setup.py
Classes with message listeners are:
> core: Add specific signals type hinting

- frida/core.py
As of Python 3.10 a new way to annotate decorators was [added](https://peps.python.org/pep-0612/#motivation).
Since `typing_extensions` now supports it, it can be a nice boost to local productivity with various IDEs.
Before:
After:
> Use ParamSpec for better type hints on `cancellable` decorator.
